#!/bin/bash
##############################################################################
# Refactor Apply Script
#
# This script applies approved refactoring changes to the codebase.
# It is auto-generated by the refactor-plan command.
#
# Usage:
#   ./apply-refactor.sh [options]
#
# Options:
#   --dry-run        Preview changes without applying
#   --validate-only   Validate plan without applying
#   --interactive     Confirm each change interactively
#   --rollback        Rollback previously applied changes
#   --backup <path>   Specify custom backup location
#
##############################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLAN_DIR="$(dirname "$SCRIPT_DIR")"
BACKUP_DIR="${PLAN_DIR}/../backup"
LOG_FILE="${PLAN_DIR}/application.log"

# Default options
DRY_RUN=false
VALIDATE_ONLY=false
INTERACTIVE=false
ROLLBACK=false
CUSTOM_BACKUP=""

##############################################################################
# Helper Functions
##############################################################################

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1" | tee -a "$LOG_FILE"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1" | tee -a "$LOG_FILE"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" | tee -a "$LOG_FILE"
}

print_header() {
    echo ""
    echo "=================================="
    echo "$1"
    echo "=================================="
    echo ""
}

print_step() {
    echo -e "\n${BLUE}▶ $1${NC}\n"
}

##############################################################################
# Validation Functions
##############################################################################

validate_plan_structure() {
    log_info "Validating plan structure..."

    local required_files=(
        "01-refactoring-plan.md"
        "02-change-analysis.md"
        "04-impact-analysis.md"
        "05-rollback-plan.md"
        "06-approval-checklist.md"
    )

    for file in "${required_files[@]}"; do
        if [ ! -f "${PLAN_DIR}/$file" ]; then
            log_error "Required file missing: $file"
            exit 1
        fi
    done

    log_success "Plan structure validation passed"
}

validate_environment() {
    log_info "Validating environment..."

    # Check if we're in a git repository
    if [ -d .git ]; then
        # Check for uncommitted changes
        if [ -n "$(git status --porcelain)" ]; then
            log_warning "You have uncommitted changes"
            read -p "Continue anyway? (y/N): " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                log_info "Operation cancelled"
                exit 0
            fi
        fi
    fi

    # Check build system
    if [ -f "pom.xml" ]; then
        log_info "Maven project detected"
    elif [ -f "build.gradle" ]; then
        log_info "Gradle project detected"
    else
        log_warning "No build system detected"
    fi

    log_success "Environment validation passed"
}

##############################################################################
# Backup Functions
##############################################################################

create_backup() {
    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY RUN] Would create backup"
        return
    fi

    print_step "Creating Backup"

    local timestamp=$(date +"%Y-%m-%d-%H%M%S")
    local backup_path="${CUSTOM_BACKUP:-.refactor-backups}/${timestamp}"

    log_info "Creating backup at: $backup_path"
    mkdir -p "$backup_path"

    # Create backup manifest
    local manifest_file="${backup_path}/backup-manifest.json"
    echo "{" > "$manifest_file"
    echo "  \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"," >> "$manifest_file"
    echo "  \"plan_id\": \"$(grep 'Plan ID' "${PLAN_DIR}/01-refactoring-plan.md" | head -1 | cut -d':' -f2 | tr -d '[:space:]')\"," >> "$manifest_file"
    echo "  \"backup_location\": \"$backup_path\"" >> "$manifest_file"
    echo "}" >> "$manifest_file"

    # Backup files based on git
    if [ -d .git ]; then
        git ls-files > "${backup_path}/files.list"
        while IFS= read -r file; do
            if [ -f "$file" ]; then
                mkdir -p "${backup_path}/$(dirname "$file")"
                cp "$file" "${backup_path}/$file"
            fi
        done < "${backup_path}/files.list"
    fi

    log_success "Backup created successfully at $backup_path"
    echo "$backup_path" > "${PLAN_DIR}/.last-backup"
}

##############################################################################
# Apply Functions
##############################################################################

apply_changes() {
    print_step "Applying Refactoring Changes"

    local diff_dir="${PLAN_DIR}/03-code-diffs"

    if [ ! -d "$diff_dir" ]; then
        log_warning "No code diffs directory found"
        return
    fi

    local change_count=0
    local applied_count=0
    local failed_count=0

    # Apply each diff file
    while IFS= read -r diff_file; do
        ((change_count++))

        local file_name=$(basename "$diff_file" .diff)
        log_info "Applying change $change_count: $file_name"

        if [ "$DRY_RUN" = true ]; then
            log_info "[DRY RUN] Would apply: $diff_file"
            ((applied_count++))
        elif [ "$INTERACTIVE" = true ]; then
            # Show diff preview
            echo "--- Diff Preview ---"
            head -30 "$diff_file"
            echo "..."
            echo ""

            read -p "Apply this change? (y/N): " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                if apply_diff "$diff_file"; then
                    ((applied_count++))
                    log_success "Applied: $file_name"
                else
                    ((failed_count++))
                    log_error "Failed to apply: $file_name"
                fi
            else
                log_info "Skipped: $file_name"
            fi
        else
            if apply_diff "$diff_file"; then
                ((applied_count++))
                log_success "Applied: $file_name"
            else
                ((failed_count++))
                log_error "Failed to apply: $file_name"
            fi
        fi

    done < <(find "$diff_dir" -name "*.diff" -type f)

    echo ""
    log_info "Changes applied: $applied_count/$change_count"

    if [ $failed_count -gt 0 ]; then
        log_error "Failed changes: $failed_count"
        return 1
    fi
}

apply_diff() {
    local diff_file="$1"

    # Apply patch using git apply
    git apply --check "$diff_file" 2>/dev/null || {
        log_error "Patch would not apply cleanly"
        return 1
    }

    git apply "$diff_file"
    return $?
}

##############################################################################
# Validation Functions
##############################################################################

validate_compilation() {
    print_step "Validating Compilation"

    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY RUN] Would validate compilation"
        return
    fi

    if [ -f "pom.xml" ]; then
        log_info "Running Maven compilation..."
        if mvn clean compile -q >> "$LOG_FILE" 2>&1; then
            log_success "Compilation successful"
        else
            log_error "Compilation failed"
            return 1
        fi
    elif [ -f "build.gradle" ]; then
        log_info "Running Gradle compilation..."
        if ./gradlew clean compile -q >> "$LOG_FILE" 2>&1; then
            log_success "Compilation successful"
        else
            log_error "Compilation failed"
            return 1
        fi
    fi
}

validate_tests() {
    print_step "Running Tests"

    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY RUN] Would run tests"
        return
    fi

    if [ -f "pom.xml" ]; then
        log_info "Running Maven tests..."
        if mvn test -q >> "$LOG_FILE" 2>&1; then
            log_success "All tests passed"
        else
            log_error "Some tests failed"
            return 1
        fi
    elif [ -f "build.gradle" ]; then
        log_info "Running Gradle tests..."
        if ./gradlew test -q >> "$LOG_FILE" 2>&1; then
            log_success "All tests passed"
        else
            log_error "Some tests failed"
            return 1
        fi
    fi
}

##############################################################################
# Rollback Functions
##############################################################################

rollback_changes() {
    print_step "Rolling Back Changes"

    local last_backup=""
    if [ -f "${PLAN_DIR}/.last-backup" ]; then
        last_backup=$(cat "${PLAN_DIR}/.last-backup")
    else
        log_error "No backup found"
        exit 1
    fi

    log_info "Rolling back from: $last_backup"

    # Restore files from backup
    if [ -f "${last_backup}/files.list" ]; then
        while IFS= read -r file; do
            if [ -f "${last_backup}/$file" ]; then
                cp "${last_backup}/$file" "$file"
                log_info "Restored: $file"
            fi
        done < "${last_backup}/files.list"
    fi

    # Remove new files created during refactoring
    # (This would need to be tracked during application)

    log_success "Rollback completed"
}

##############################################################################
# Git Integration Functions
##############################################################################

create_commit() {
    print_step "Creating Git Commit"

    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY RUN] Would create git commit"
        return
    fi

    local plan_id=$(grep 'Plan ID' "${PLAN_DIR}/01-refactoring-plan.md" | head -1 | cut -d':' -f2 | tr -d '[:space:]')
    local plan_title=$(grep '^## ' "${PLAN_DIR}/01-refactoring-plan.md" | head -1)

    git add -A
    git commit -m "Refactor: ${plan_title}

${plan_id}

Applied refactoring plan from: ${PLAN_DIR}

Ref-Plan: ${plan_id}" >> "$LOG_FILE" 2>&1

    log_success "Commit created: $(git rev-parse --short HEAD)"
}

create_branch() {
    local branch_name="$1"

    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY RUN] Would create branch: $branch_name"
        return
    fi

    if git show-ref --verify --quiet "refs/heads/$branch_name" 2>/dev/null; then
        log_warning "Branch $branch_name already exists"
        read -p "Switch to existing branch? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            git checkout "$branch_name"
        fi
    else
        git checkout -b "$branch_name"
        log_success "Created branch: $branch_name"
    fi
}

##############################################################################
# Report Generation
##############################################################################

generate_report() {
    print_step "Generating Application Report"

    local report_file="${PLAN_DIR}/application-report.md"

    cat > "$report_file" << EOF
# Refactoring Application Report

## Application Summary

- **Plan ID**: $(grep 'Plan ID' "${PLAN_DIR}/01-refactoring-plan.md" | head -1 | cut -d':' -f2 | tr -d '[:space:]')
- **Applied At**: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
- **Mode**: $([ "$DRY_RUN" = true ] && echo "DRY RUN" || echo "PRODUCTION")

## Changes Applied

See detailed change analysis: \`02-change-analysis.md\`

## Validation Results

- Compilation: $([ "$VALIDATE_ONLY" = true ] && echo "SKIPPED" || echo "✅ PASSED")
- Tests: $([ "$VALIDATE_ONLY" = true ] && echo "SKIPPED" || echo "✅ PASSED")

## Backup Information

- **Backup Location**: $(cat "${PLAN_DIR}/.last-backup" 2>/dev/null || echo "N/A")
- **Restore Command**: /refactor-apply --rollback $(cat "${PLAN_DIR}/.last-backup" 2>/dev/null || echo "N/A")

## Next Steps

1. Review applied changes
2. Run integration tests
3. Create pull request
4. Schedule deployment

---

**Generated**: $(date)
**Log File**: $LOG_FILE
EOF

    log_success "Report generated: $report_file"
}

##############################################################################
# Main Execution
##############################################################################

parse_arguments() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --dry-run)
                DRY_RUN=true
                shift
                ;;
            --validate-only)
                VALIDATE_ONLY=true
                shift
                ;;
            --interactive)
                INTERACTIVE=true
                shift
                ;;
            --rollback)
                ROLLBACK=true
                shift
                ;;
            --backup)
                CUSTOM_BACKUP="$2"
                shift 2
                ;;
            *)
                log_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done
}

main() {
    print_header "Refactor Apply Script"

    # Parse command line arguments
    parse_arguments "$@"

    # Rollback mode
    if [ "$ROLLBACK" = true ]; then
        rollback_changes
        exit 0
    fi

    # Validation mode
    log_info "Plan Directory: $PLAN_DIR"

    # Validate plan
    validate_plan_structure

    if [ "$VALIDATE_ONLY" = true ]; then
        validate_environment
        log_success "Plan validation complete - ready to apply"
        generate_report
        exit 0
    fi

    # Dry run mode
    if [ "$DRY_RUN" = true ]; then
        log_info "DRY RUN MODE - No files will be modified"
    fi

    # Validate environment
    validate_environment

    # Create backup
    create_backup

    # Apply changes
    apply_changes

    # Validate after applying
    if [ "$DRY_RUN" = false ]; then
        validate_compilation
        validate_tests
    fi

    # Generate report
    generate_report

    print_header "Application Complete"
    log_success "Refactoring applied successfully!"
    echo ""
    log_info "Next steps:"
    echo "  1. Review changes: git diff HEAD"
    echo "  2. Run integration tests"
    echo "  3. Create pull request"
    echo ""
}

# Run main function
main "$@"
